wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1679339634.298585
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.4
      5: 0.13.7
      8:
      - 1
      - 5
add_hp:
  desc: null
  value: false
add_lp:
  desc: null
  value: false
adjoint:
  desc: null
  value: false
adjoint_method:
  desc: null
  value: adaptive_heun
adjoint_step_size:
  desc: null
  value: 1
cuda:
  desc: null
  value: 0
d:
  desc: null
  value: 3
dataset:
  desc: null
  value: texas
deg_normalised:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
dropout:
  desc: null
  value: 0.7
early_stopping:
  desc: null
  value: 200
earlystopxT:
  desc: null
  value: 3
edge_weights:
  desc: null
  value: true
entity:
  desc: null
  value: sheafnn
epochs:
  desc: null
  value: 1500
evectors:
  desc: null
  value: 0
folds:
  desc: null
  value: 10
graph_size:
  desc: null
  value: 183
hidden_channels:
  desc: null
  value: 20
input_dim:
  desc: null
  value: 1703
input_dropout:
  desc: null
  value: 0.0
int_method:
  desc: null
  value: null
layers:
  desc: null
  value: 4
left_weights:
  desc: null
  value: true
linear:
  desc: null
  value: false
lr:
  desc: null
  value: 0.01
max_iters:
  desc: null
  value: 100
max_nfe:
  desc: null
  value: 1000
max_t:
  desc: null
  value: 1.0
max_test_steps:
  desc: null
  value: 100
min_acc:
  desc: null
  value: 0.0
model:
  desc: null
  value: BundleSheaf
no_early:
  desc: null
  value: false
normalised:
  desc: null
  value: true
orth:
  desc: null
  value: householder
output_dim:
  desc: null
  value: 5
right_weights:
  desc: null
  value: true
second_linear:
  desc: null
  value: false
seed:
  desc: null
  value: 43
sheaf_act:
  desc: null
  value: tanh
sheaf_decay:
  desc: null
  value: 0.0005
step_size:
  desc: null
  value: 1
stop_strategy:
  desc: null
  value: loss
tol_scale:
  desc: null
  value: 1.0
tol_scale_adjoint:
  desc: null
  value: 1.0
use_act:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.0005
